### ISSUE TITLE
Reagarding reranker.py

### ISSUE THREAD

**Issue by alstn7** [zomss/Co-Prompt#3]
Hi!

First of all, thank you for your work! 

I was looking at your code and came up with a question regarding the python code reranker.py.

I understand that the reranker.py file is where you get the log-likelihood, which you in your paper describe as the "relevance score between document-query pairs." 
And in they paper, it says that the document and prompt are the input and the output is the query corresponding to the input document.

However in your code, 
`input = [
            torch.LongTensor(i + self.tokenizer.convert_tokens_to_ids(self.tokenizer.tokenize(q))).to(self.device)
            for i, q in zip(input, queries)
        ]`

query is concatenated to the document and prompt. Leading to the model input to be formatted as Passage: {document}{delimiter}{prompt}{delimiter}{query}.

Is this correct? Am I misunderstanding the paper? 
and if so, could you be kind enough to explain on this matter?

Thank you so much!!!

**Comment by zomss** [comment]
Thanks for the question.

First, in our work, we measure the relevance score between document-query pairs by query generation score (i.e., the likelihood of the token included in the query).

For example, the format of input for measuring relevance score is followed as:
"{Document}

Please write a question bsaed on this passage

{Query}"

In our implementation, we transfer the query included in the input to LLM and calculate the likelihood score from the outputs of LLM.

If you have any further questions or something to clarify, feel free to ask!

**Comment by alstn7** [comment]
Thank you for your clarificiation! Have a good day!
